language: node_js

sudo: required

node_js:
  - "node"

services:
  - postgresql

before_install:
  - npm install -g sequelize

install:
  - npm install

before_script:
  - psql -c 'create database postit;' -U postgres

cache:
  directories:
    - "node_modules"

after_success:
  - npm run cover

after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

script: npm run test