language: node_js
node_js:
  - "iojs"
  - "7"

services:
  - postgresql

before_script:
  - psql -c 'create database postit;' -U postgres
  - npm  install

cache:
  directories:
    - "node_modules"

script: npm run test